export interface Vehicle {
  id?: number; // Optional since it's generated by the backend
  uuid: string;
  registrationStatus: RegistrationStatus;
  startDate: string;
  endDate: string;
  brand: string;
  type: string;
}
export enum RegistrationStatus {
  REGISTERED = 'REGISTERED',
  DEREGISTERED = 'DEREGISTERED'
}
