export interface Vehicle {
  id?: number; // Optional since it's generated by the backend
  uuid: string;
  registrationStatus: RegistrationStatus;
  recordCategory: RecordCategory;
  startDate: Date;
  endDate: Date;
  brand: string;
  type: string;
}
export enum RegistrationStatus {
  REGISTERED = 'REGISTERED',
  DEREGISTERED = 'DEREGISTERED'
}

export enum RecordCategory {
  COMMERCIAL = 'COMMERCIAL',
  PERSONAL = 'PERSONAL'
}
